WIP Add AccessTokenCreator
mtarld/api-platform-ms-bundle pull request #37
Opened 2020-11-28 18:04 UTC by ismail1432

Should resolve #35 

Not sure about : 

- the namespace
- credential in PHP doc
- implementation

- [ ] Tests
- [ ] Documentation

2020-12-05 21:42 UTC, ismail1432 commented
@mtarld I rebase with master, There is not test yet but I'm working on,  BTW I have some question 

- I'm not sure about the namespace it was `Security` and I replace by `AccessToken` and I'm still not sure
- I remove [all service declaration ](https://github.com/mtarld/api-platform-ms-bundle/pull/37/commits/2f4bc98a477bced64a7e2cca8a6cce637af495c6#diff-4a3af44c7eda2b193f97cbbaeb52568de5ce4f6843acb8416a4396ce7981190fL31) it seems useless but I don't know if I keep this change in this PR, WDYT ?

2020-12-05 21:57 UTC, mtarld commented
> @mtarld I rebase with master, There is not test yet but I'm working on, BTW I have some question
> 
> * I'm not sure about the namespace it was `Security` and I replace by `AccessToken` and I'm still not sure

Actullay, I'm wondering if the "AccessToken" stuff should simply go in the `HttpClient` namespace as it's just a part of the HTTP Client. WDYT?

2021-01-14 08:23 UTC, mtarld requested changes
I really like that PR, the feature will be truly powerful! Many thanks :slightly_smiling_face: 

That's almost good. Some little comments though.

2021-01-14 08:23 UTC, mtarld commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +        $container->registerForAutoconfiguration(AuthenticationHeaderProviderInterface::class)->addTag('api_platform_ms.authentication_header_provider')
```suggestion
        $container->registerForAutoconfiguration(AuthenticationHeaderProviderInterface::class)->addTag('api_platform_ms.authentication_header_provider');
```

2021-01-14 08:23 UTC, mtarld commented on src/Resources/doc/tools/authentication-header-provider.md
> +TODO Talk about tagged iterators, priority and link to the Symfony doc
I'll give you the content ASAP

2021-01-14 08:23 UTC, mtarld commented on tests/Fixtures/App/src/Authentication/BasicAuthenticationHeaderProvider.php
> +    private $enable = false;
Could you rename `enable` to `enabled` and `setEnable` to `setEnabled`? (Same goes for `BearerAuthenticationHeaderProvider`)

2021-01-14 08:23 UTC, mtarld commented on tests/Fixtures/App/src/Authentication/BasicAuthenticationHeaderProvider.php
> +    private $enable = false;
Can you add phpdoc as well?

2021-01-14 08:23 UTC, mtarld commented on tests/HttpClient/HttpClientTest.php
> +    public function testAuthenticationHeaders($microservice, $method, $uri, array $expectedAuthenticationHeader): void
```suggestion
    public function testAuthenticationHeaders(string $microservice, string $method, string $uri, array $expectedAuthenticationHeader): void
```

2021-01-14 13:13 UTC, ismail1432 commented
TY thanks for review I'll do them asap

2021-01-16 09:54 UTC, mtarld commented on src/Resources/doc/tools/authentication-header-provider.md
> +TODO Talk about tagged iterators, priority and link to the Symfony doc
Thanks for the doc part, it's perfect :+1:

2021-01-16 09:55 UTC, mtarld approved these changes
LGTM! Many thanks @ismail1432

2021-01-16 10:23 UTC, merged