WIP: Add event
mtarld/api-platform-ms-bundle pull request #49
Opened 2021-02-15 23:00 UTC by ismail1432

Dispatch event when a Request is trigger

- [ ] Dispatch
- [ ] Tests

2021-02-22 13:56 UTC, mtarld requested changes

2021-02-22 13:56 UTC, mtarld commented on src/HttpClient/GenericHttpClient.php
> +        EventDispatcherInterface $dispatcher = null
```suggestion
        ?EventDispatcherInterface $dispatcher = null
```

2021-02-22 13:56 UTC, mtarld commented on src/HttpClient/GenericHttpClient.php
> +        $response = $this->httpClient->request($method, $uri, $options);
Here, `HttpClientInterface::request` can throw a `TransportExceptionInterface`.
But if that exception is thrown, we won't dispatch the `RequestEvent`.
Maybe we can surround it with a try/catch block a dispatch that event in the finally? (with a nullable `Response` then)

2021-02-22 13:56 UTC, mtarld commented on src/Event/RequestEvent.php
> + * @final
Could you add `psalm-immutable`?

2021-02-22 13:56 UTC, mtarld commented on CHANGELOG.md
> +* Added the `RequestEvent` dispatched once a request is send
```suggestion
* Added dispatching of a `RequestEvent` once a request is sent
```

2021-02-22 13:56 UTC, mtarld commented on tests/Event/RequestEventTest.php
> +    public function testEventIsDispatch()
This test should be in `HttpClientTest` IMHO

2021-02-22 13:56 UTC, mtarld commented on tests/Event/RequestEventTest.php
> +    public function testEventIsDispatch()
```suggestion
    public function testEventIsDispatched(): void
```

2021-02-22 13:56 UTC, mtarld commented on tests/Event/RequestEventTest.php
> +            $eventDispatcherMock = $this->createMock(EventDispatcherInterface::class)
```suggestion
            $eventDispatcherSpy = $this->createMock(EventDispatcherInterface::class)
```

2021-02-22 13:56 UTC, mtarld commented on tests/Event/RequestEventTest.php
> +        $eventDispatcherMock->expects($this->once())->method('dispatch');
You can as well use `with(...arguments)` to verify that the dispatched event is the expected one.

2021-02-22 13:56 UTC, mtarld commented on tests/Event/RequestEventTest.php
> +    public function testGetter(Microservice $microservice, string $method, string $uri, array $options, ResponseInterface $response, string $content)
IMHO, this test is not needed as `RequestEvent` is an immutable POPO

2021-02-22 13:56 UTC, mtarld commented on src/HttpClient/GenericHttpClient.php
> +            $this->dispatcher->dispatch(new RequestEvent($microservice, $method, $uri, $options, $response));
Could you add `RequestEvent` to preloading?

```php
// Help opcache.preload discover always-needed symbols
class_exists(RequestEvent::class);
```

2021-02-23 13:20 UTC, mtarld requested changes
Almost good :wink:

2021-02-23 13:20 UTC, mtarld commented on src/HttpClient/GenericHttpClient.php
> +            $response = $exception->getResponse();
`getResponse` is part of `HttpExceptionInterface` and not `ExceptionInterface`.
Therefore, you should test if the exception is a `HttpExceptionInterface` (using `instanceof`?) and set the response only if it is

2021-02-23 13:20 UTC, mtarld commented on src/HttpClient/GenericHttpClient.php
> +                $this->dispatcher->dispatch(new RequestEvent($microservice, $method, $uri, $options, $response));
```suggestion
                $this->dispatcher->dispatch(new RequestEvent($microservice, $method, $uri, $options, $response ?? null));
```

2021-02-23 13:20 UTC, mtarld commented on tests/HttpClient/HttpClientTest.php
> +        $httpClient->request($microservice, $method, $uri);
Is this line needed?

2021-02-23 13:20 UTC, mtarld commented on composer.json
> +    "psr/log": "^1.0"
I don't this is part of the current PR ;)

2021-02-23 13:20 UTC, mtarld commented on tests/HttpClient/HttpClientTest.php
> +    public function testEventIsDispatched(string $method, string $uri, string $format, string $header): void
Maybe we can find a more meaningful name for `$header`? Something like `$mimeType`?

2021-02-23 13:21 UTC, ismail1432 commented on composer.json
> +    "psr/log": "^1.0"
wrong cherry-pick :stuck_out_tongue:

2021-02-23 13:55 UTC, mtarld requested changes

2021-02-23 13:55 UTC, mtarld commented on src/Event/RequestEvent.php
> +    public function __construct(Microservice $microservice, string $method, string $uri, array $options, ?ResponseInterface $response = null)
I'd rather write `?ResponseInterface $response)` because I don't see the benefit to set a default value here

2021-02-23 14:40 UTC, ismail1432 commented on src/Event/RequestEvent.php
> +    public function __construct(Microservice $microservice, string $method, string $uri, array $options, ?ResponseInterface $response = null)
good point

2021-02-23 18:14 UTC, mtarld approved these changes
LGTM! Many thanks!

2021-04-02 08:01 UTC, merged