WIP: Add log for each request
mtarld/api-platform-ms-bundle pull request #52
Opened 2021-02-19 22:35 UTC by ismail1432

Should fix #47 wait #49 before merging

2021-04-02 08:02 UTC, mtarld commented
https://github.com/mtarld/api-platform-ms-bundle/pull/49 is merged :tada: 
You can now rebase your branch

2021-04-02 17:07 UTC, ismail1432 commented
I Rebased and add tests :fire: 
cc @mtarld

2021-04-02 17:51 UTC, mtarld requested changes

2021-04-02 17:51 UTC, mtarld commented on src/EventListener/RequestLoggerListener.php
> +            'options' => $event->getOptions(),
I'm afraid that options can't be logged.
In fact, authentication information (such as password) could be there. Have a look at https://symfony.com/doc/current/http_client.html#authentication

A workaround could be to exclude `auth_*` and `header` options.
But TBH, it's kind of hacky and I don't see any option that worth to be logged.

WDYT?

2021-04-02 17:51 UTC, mtarld commented on src/EventListener/RequestLoggerListener.php
> +        $this->logger->debug('[GenericHttpClient] for Microservice "{microservice_name}" calling {method} {url}', [
I'm not sure about that message. The `GenericHttpClient` is not internal but will rarely be used directly. Most of the time, users will use the `MicroserviceHttpClient` (which internally use the `GenericHttpClient`).

Maybe we can log something more generic like `[{microservice_name} microservice] Calling "{method} {url}"`.
This will result as `[Product microservice] Calling "GET /foo"`.

WDYT?

2021-04-02 17:51 UTC, mtarld commented on tests/EventListener/RequestLoggerListenerTest.php
> +     * @dataProvider microserviceProvider
```suggestion
     * @dataProvider microserviceDataProvider
```
for consistency

2021-04-02 17:51 UTC, mtarld commented on tests/EventListener/RequestLoggerListenerTest.php
> +class RequestLoggerListenerTest extends KernelTestCase
As you don't use the kernel, you can extend `PHPUnit\Framework\TestCase` only

2021-04-02 17:57 UTC, mtarld commented on src/EventListener/RequestLoggerListener.php
> +class RequestLoggerListener implements EventSubscriberInterface
You can add author tags as well :slightly_smiling_face:

2021-04-02 21:22 UTC, ismail1432 commented on tests/EventListener/RequestLoggerListenerTest.php
> +class RequestLoggerListenerTest extends KernelTestCase
TY, #WrongHabit :smile:

2021-04-02 21:23 UTC, ismail1432 commented on src/EventListener/RequestLoggerListener.php
> +class RequestLoggerListener implements EventSubscriberInterface
done + I add `@final` and `opcache.preload`

2021-04-02 21:35 UTC, ismail1432 commented on src/EventListener/RequestLoggerListener.php
> +            'options' => $event->getOptions(),
:100:

2021-04-02 21:35 UTC, ismail1432 commented on src/EventListener/RequestLoggerListener.php
> +        $this->logger->debug('[GenericHttpClient] for Microservice "{microservice_name}" calling {method} {url}', [
:100: again :sweat_smile:

2021-04-02 21:35 UTC, ismail1432 commented on tests/EventListener/RequestLoggerListenerTest.php
> +     * @dataProvider microserviceProvider
done

2021-04-03 09:05 UTC, mtarld requested changes
Almost good :slightly_smiling_face: 
One more thing, I'm wondering if the logging behavior should be configurable (ie: enabled/disabled accordingly to a configuration). WDYT?

2021-04-03 09:05 UTC, mtarld commented on src/EventListener/RequestLoggerListener.php
> +        $this->logger->debug('Microservice "{microservice_name}" calling {method} {url}', [
```suggestion
        $this->logger->debug('Microservice "{microservice_name}" calling "{method} {url}".', [
```

2021-04-03 22:36 UTC, ismail1432 commented
>One more thing, I'm wondering if the logging behavior should be configurable (ie: enabled/disabled accordingly to a configuration).

You have a good idea as usual :+1: 
Config should be global or per MS or both?

2021-04-06 07:48 UTC, mtarld commented
> Config should be global or per MS or both?

The config should be global. For instance: "I'm a microservice and I will call the X microservice".
Therefore I can see a problem with the current log sentence. Because $microservice is in fact representing the **targeted** microservice
IMHO, the sentence should be instead `Calling "{microservice_name}" microservice: "{method} {url}".`

2021-06-07 09:11 UTC, ismail1432 commented
Hey @mtarld 
I'm very sorry for the delay, I'll finish it very soon :rocket:

2021-07-27 00:17 UTC, ismail1432 commented on src/EventListener/RequestLoggerListener.php
> +class_exists(RequestEvent::class);
done

2021-07-27 00:20 UTC, ismail1432 commented
⚠️  Missing changelog

2021-11-10 22:29 UTC, ismail1432 commented on .php-cs-fixer.php
> +$finder = PhpCsFixer\Finder::create()
should be done in https://github.com/mtarld/api-platform-ms-bundle/pull/55

2021-11-10 22:31 UTC, ismail1432 commented on CHANGELOG.md
> +* Added `RequestLoggerListener` to log each request
maybe add the fact that it's disable by default ?

2021-11-10 22:31 UTC, ismail1432 commented on composer.json
> +    "friendsofphp/php-cs-fixer": "^3.1",
should be done in https://github.com/mtarld/api-platform-ms-bundle/pull/55

2021-11-10 22:31 UTC, ismail1432 commented on src/DependencyInjection/Configuration.php
> +                ->scalarNode('log_request')->defaultFalse()->end()
logging is false by default 🎉

2021-11-10 22:31 UTC, ismail1432 commented on src/Validator/ApiResourceExistValidator.php
> +        } catch (HttpClientExceptionInterface|SerializerExceptionInterface $e) {
should be done https://github.com/mtarld/api-platform-ms-bundle/pull/55

2021-11-10 22:31 UTC, ismail1432 commented on tests/EventListener/RequestLoggerListenerTest.php
> +    public function testRequestIsLoggedViaAnEvent(Microservice $microservice, string $microserviceName, string $method, string $uri)
missin return type

2021-11-12 01:56 UTC, chalasr commented on src/DependencyInjection/Configuration.php
> +                ->scalarNode('log_request')->defaultFalse()->end()
What about `true` in debug mode? https://github.com/symfony/symfony/blob/8eed84bb2df613101949ca2e786ac383d2f349fd/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1154

2021-11-12 01:56 UTC, chalasr commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +        $container->setParameter('api_platform_ms.log_request', $config['log_request']);
Here the event listener service definition could be removed from the container when `log_request` is `false` instead. That will allow removing the compiler pass as the `kernel.event_listener` tag can be added to the xml definition. This parameter won't be useful anymore also

2021-11-12 01:56 UTC, chalasr commented on CHANGELOG.md
> +* Added `RequestLoggerListener` to log each request
also I suggest talking about the option rather than the class, or both eventually

2021-11-12 14:22 UTC, art-cg commented on composer.json
> +    "friendsofphp/php-cs-fixer": "^3.1",
Is merged

2021-11-12 14:23 UTC, art-cg commented on src/Validator/ApiResourceExistValidator.php
> +        } catch (HttpClientExceptionInterface|SerializerExceptionInterface $e) {
Is merged

2021-11-12 22:34 UTC, mtarld requested changes

2021-11-12 22:34 UTC, mtarld commented on src/DependencyInjection/Configuration.php
> +    public function __construct(bool $debug)
I think what @chalasr meant was to rely on the debug mode of Symfony instead

2021-11-12 22:34 UTC, mtarld commented on src/DependencyInjection/Compiler/RegisterRequestLoggerListenerPass.php
> +        if (true === $container->getParameter('api_platform_ms.log_request')) {
If false, you can remove the service definition

2021-11-12 22:40 UTC, chalasr commented on src/DependencyInjection/Configuration.php
> +    public function __construct(bool $debug)
That's the way :) What is remains to do is to pass the `kernel.debug` parameter when calling this constructor, which is the job of `ExtensionInterface::getConfiguration()`. 
See https://symfony.com/doc/current/configuration/using_parameters_in_dic.html

2021-11-13 16:33 UTC, ismail1432 commented on src/DependencyInjection/Configuration.php
> +    public function __construct(bool $debug)
Genius :bulb:

2021-11-13 16:34 UTC, ismail1432 commented on src/DependencyInjection/Compiler/RegisterRequestLoggerListenerPass.php
> +        if (true === $container->getParameter('api_platform_ms.log_request')) {
Yep I did in `ApiPlatformMsExtension` is it OK for You?

2021-11-13 16:35 UTC, ismail1432 commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +        $container->setParameter('api_platform_ms.log_request', $config['log_request']);
Thanks for the idea, I did it :+1: 

>This parameter won't be useful anymore also
It allow en user to enable/disable, we should keep it isn't It ?

2021-11-13 18:25 UTC, chalasr commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +            $container->removeDefinition('api_platform_ms.request_logger_listener');
The issue with using `"%kernel.debug%"` as default value for the `log_request` config option is that this code cannot be reached. At this stage `$container->getParameter('api_platform_ms.log_request')` equals the string `"%kernel.debug%"`, not the resolved value of the `%kernel.debug%` parameter.

I suggest to go back to your original approach i.e. passing the debug mode as constructor argument to the `Configuration` class (using `return new Configuration($container->getParameter('kernel.debug');` in `ApiPlatformMsExtension::getConfiguration()`), as demonstrated in https://symfony.com/doc/current/configuration/using_parameters_in_dic.html

2021-11-13 18:26 UTC, chalasr commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +        $container->setParameter('api_platform_ms.log_request', $config['log_request']);
What I mean is that the config option does not need to be set as container parameter, those are two different things. Here you can just change the condition below to make it use if (!$config['log_request']), and remove that setParameter() :)

2021-11-13 20:54 UTC, ismail1432 commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +        $container->setParameter('api_platform_ms.log_request', $config['log_request']);
I got it :+1: 

THANKS

2021-11-13 20:55 UTC, ismail1432 commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +            $container->removeDefinition('api_platform_ms.request_logger_listener');
I updated, Thanks Robin

2021-11-13 21:14 UTC, chalasr approved these changes
Nice! 👌

2021-11-15 08:20 UTC, mtarld approved these changes
LGTM!

2021-11-15 08:20 UTC, merged

2021-11-15 08:21 UTC, mtarld commented
Thank you @ismail1432!