chore: bump friendsofphp/php-cs-fixer from 2 => 3
mtarld/api-platform-ms-bundle pull request #55
Opened 2021-11-10 14:29 UTC by art-cg

PhpStorm is nagging me about the outdated php-cs-fixer version.

Php 7.1.3 is still supported.
`"php": "^7.1.3 || ^8.0",`
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/composer.json

2021-11-10 15:42 UTC, mtarld requested changes
Thanks for the update!

I think you must update the config filename:
```
Configuration file `.php_cs` is outdated, rename to `.php-cs-fixer.php`.  
```

2021-11-10 15:47 UTC, art-cg commented
You are rigth. I need to put more work on this. I saw this after i enabled my Github Actions.
Renaming is not the only task. The content of the file is outdated too.

2021-11-10 22:28 UTC, ismail1432 commented
Thanks @art-cg 
You can take a look at https://github.com/mtarld/api-platform-ms-bundle/pull/57 I implement changes to pass my PR https://github.com/mtarld/api-platform-ms-bundle/pull/52 😅

2021-11-11 10:25 UTC, art-cg commented
@ismail1432 Thanks for the info.
I changed the cache file to the default one and changed it in gitignore too.
I added a little helper entry in composer.json

Test on GitHub Actions looks good. Locally on windows it gives warnings for lineEndings.
`<error severity="warning" source="PHP-CS-Fixer.line_ending" message="Found violation(s) of type: line_ending"/>`
https://github.com/art-cg/api-platform-ms-bundle/runs/4176710611?check_suite_focus=true

2021-11-12 09:30 UTC, mtarld approved these changes
Just a little review :slightly_smiling_face:

2021-11-12 09:30 UTC, mtarld commented on .php-cs-fixer.php
> +;
Missing empty line here

2021-11-12 11:23 UTC, art-cg commented on .php-cs-fixer.php
> +;
I added the new line at the end

2021-11-12 11:27 UTC, merged

2021-11-12 11:27 UTC, mtarld commented
Thank you @art-cg!