Feature/replace deprecated container call
mtarld/api-platform-ms-bundle pull request #67
Opened 2021-11-19 21:05 UTC by Chris53897

Hi. Proof of concept for my (thats another account from me) idea in #65
A lot of code changes just to support symfony 4.4 :(
It works according to the test pipeline.
I don't have PHP 7.1 on my pc to verify it local.

If you find a simpler and better solution i would be glad.

Greetz

2021-11-26 09:13 UTC, mtarld requested changes

2021-11-26 09:13 UTC, mtarld commented on tests/BcLayer/BcLayerWebTestCase.php
> +namespace Mtarld\ApiPlatformMsBundle\Tests\BcLayer;
I'd rather have put those classes in `Mtarld\ApiPlatformMsBundle\Tests`

2021-11-26 09:13 UTC, mtarld commented on tests/BcLayer/BcLayerWebTestCase.php
> +if (Kernel::VERSION_ID <= 50000) {
I don't like having conditional class definitions (and checking the kernel version id). WDYT about:
```php
<?php

namespace Mtarld\ApiPlatformMsBundle\Tests;

use LogicException;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException;

// Remove after support of symfony support of 4.4 is dropped
abstract class BcLayerWebTestCase extends WebTestCase
{
    private static $kernelContainer;

    protected static function bootKernel(array $options = [])
    {
        $kernel = parent::bootKernel($options);

        self::$kernelContainer = $kernel->getContainer();

        return $kernel;
    }

    protected static function getContainer(): ContainerInterface
    {
        if (method_exists(parent::class, 'getContainer')) {
            return parent::getContainer();
        }

        if (!static::$booted) {
            static::bootKernel();
        }

        try {
            return self::$kernelContainer->get('test.service_container');
        } catch (ServiceNotFoundException $e) {
            throw new LogicException('Could not find service "test.service_container". Try updating the "framework.test" config to "true".', 0, $e);
        }
    }
}
```

(Same for BcLayerKernelTestCase)

2021-12-13 11:51 UTC, Chris53897 commented on tests/BcLayer/BcLayerWebTestCase.php
> +if (Kernel::VERSION_ID <= 50000) {
Sorry for late response (newborn baby).
Thanks for looking into this.
I changed it to your idea.

2021-12-13 13:18 UTC, Chris53897 commented
Test for PHP 7.4 8.0 and 8.1 fail. info: First run after 5.4 is stable.
7.4 and 8.0 for Remaining self deprecation notices
8.1 because of api-platform

I guess these should be handled in an different PR. WDYT?

2021-12-17 09:44 UTC, mtarld commented
Yes indeed. Let's do that!

2021-12-17 10:17 UTC, mtarld commented
Here we are: https://github.com/mtarld/api-platform-ms-bundle/pull/68

2021-12-17 10:25 UTC, mtarld approved these changes
Thank you @Chris53897!

2022-01-06 16:42 UTC, Chris53897 commented
@mtarld Could you please aprove the workflow to run the github action tests. I guess i did the rebase wrong. Sorry for that.

2022-01-07 08:13 UTC, merged

2022-01-07 08:14 UTC, mtarld commented
Thank you @Chris53897!