feat: add php8 typehints, update composser and GitHub actions
mtarld/api-platform-ms-bundle pull request #78
Opened 2022-01-07 19:26 UTC by Chris53897

Hi,
WIP
One Test fails. I guess another Exception is Raised after TypeHints are added. I tried InvalidArgumentException but that was not working. Maybe you have an idea to solve this. Or if this test is neccessary, yet after adding the TypeHints.

I have not much knowledge about Psalm. 
I will fix Codeing Standards later. I have some problems with Line Endings, and running locally needs manual adjustments for me.

I noticed that "psalm/plugin-phpunit": "^0.15", will not upgrade with `composer update` "psalm/plugin-phpunit": "^0.16",
So i set this manually.

Greetz

2022-01-10 17:51 UTC, mtarld requested changes
Really nice job! :100: 

Psalm is failing because `DocblockTypeContradiction` is useless now.
And PHPUnit is failing because serializer groups annotations (and soon PHP8 serializer groups attributes) should be put on the constructor argument. This will be resolved when using constructor property promotion everywhere

Thanks for the work for far :slightly_smiling_face:

2022-01-10 17:51 UTC, mtarld commented on composer.json
> +    "php": "^8.0",
Let's put `>=8.0` instead (as suggested by Symfony)

2022-01-10 17:51 UTC, mtarld commented on src/Collection/Collection.php
> +    private ?Microservice $microservice;
```suggestion
    private ?Microservice $microservice = null;
```
So you can remove the set in the constructor

2022-01-10 17:51 UTC, mtarld commented on src/Collection/PaginatedCollectionIterator.php
> +    public function __construct(private GenericHttpClient $httpClient, private SerializerInterface $serializer)
Let's put each argument on its own line for consistency, WDYT?

2022-01-10 17:51 UTC, mtarld commented on src/Collection/Pagination.php
> +    public function __construct(private string $current,
```suggestion
    public function __construct(
        private string $current,
```

2022-01-10 17:51 UTC, mtarld commented on src/Collection/PaginatedCollectionIterator.php
> +     * @throws ClientExceptionInterface
The `ExceptionInterface` is already holding those exceptions

2022-01-10 17:51 UTC, mtarld commented on src/Dto/ApiResourceDtoTrait.php
> +    protected ?string $iri;
```suggestion
    protected ?string $iri = null;
```

2022-01-10 17:51 UTC, mtarld commented on src/Dto/ApiResourceExistenceCheckerPayload.php
> +    public array $iris;
Why not using the constructor property promotion here?

2022-01-10 17:51 UTC, mtarld commented on src/Dto/ApiResourceExistenceCheckerPayload.php
>       *     @Assert\NotBlank(allowNull=false)
You can use PHP attributes now :tada:

2022-01-10 17:51 UTC, mtarld commented on src/Event/RequestEvent.php
> +    public function __construct(private Microservice $microservice,
```suggestion
    public function __construct(
        private Microservice $microservice,
```
Same for other occurrences

2022-01-10 17:51 UTC, mtarld commented on src/Exception/ResourceValidationException.php
> +    public function __construct(private mixed $value, private ConstraintViolationList $violations)
Same here (one on each line), and same for every other occurrences

2022-01-10 17:51 UTC, mtarld commented on src/HttpClient/GenericHttpClient.php
>          iterable $authenticationHeaderProviders = [],
I think we can use constructor property promotion here as well

2022-01-10 17:51 UTC, mtarld commented on src/Microservice/Microservice.php
> +    public function __construct(string $name, string $baseUri, private string $apiPath, string $format)
Same here, you can use constructor property promotion even with PHP attributes, eg:
```php
public function __construct(
    #[Assert\NotBlank]
    private string $name,
    
    // ...
) {
}

2022-01-10 17:51 UTC, mtarld commented on src/Serializer/NameConverterAwareTrait.php
> +    protected ?NameConverterInterface $nameConverter;
```suggestion
    protected ?NameConverterInterface $nameConverter = null;
```

2022-01-10 17:51 UTC, mtarld commented on src/Validator/ApiResourceExist.php
> +    public function __construct(public null|string|array $microservice = null, ?bool $skipOnError = null, ?string $message = null, ?array $groups = null, mixed $payload = null, array $options = [])
```suggestion
    public function __construct(public array|string|null $microservice = null, ?bool $skipOnError = null, ?string $message = null, ?array $groups = null, mixed $payload = null, array $options = [])
```

2022-01-10 17:51 UTC, mtarld commented on src/Validator/ApiResourceExist.php
>       * @psalm-suppress DocblockTypeContradiction
Can be removed :tada:

2022-01-10 17:51 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Color.php
>      public function __construct(int $id, string $hex)
Let's use constructor property promotion here as well (and for other resources)

2022-01-10 17:51 UTC, mtarld commented on tests/Microservice/MicroservicePoolTest.php
> +        $validatorInterface = static::getContainer()->get(ValidatorInterface::class);
```suggestion
        $validator = static::getContainer()->get(ValidatorInterface::class);
```

2022-01-10 17:51 UTC, mtarld commented on tests/Validator/ApiResourceExistValidatorTest.php
```suggestion
```

2022-01-10 19:59 UTC, Chris53897 commented on tests/Fixtures/App/src/Entity/Color.php
>      public function __construct(int $id, string $hex)
If i do this the info `@Groups({"read"})` will be lost. Or how do i handle this?

2022-01-10 20:04 UTC, Chris53897 commented on src/Validator/ApiResourceExist.php
>       * @psalm-suppress DocblockTypeContradiction
I am not  sure what can be removed.

2022-01-10 20:19 UTC, Chris53897 commented on tests/Fixtures/App/src/Entity/Color.php
>      public function __construct(int $id, string $hex)
Do you mean something like this?

```
#[ApiResource(normalizationContext: ['groups' => ['read']])]
class Color
{
    public function __construct(
        #[ApiProperty(identifier: true)] #[Groups('read')] int $id,
        #[Groups('read')] public string $hex)
    {
    }
}
```

I got this Exception
`Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException : Can't get a way to read the property "id" in class "Mtarld\ApiPlatformMsBundle\Tests\Fixtures\App\src\Entity\Color".`

2022-01-11 08:12 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Color.php
>      public function __construct(int $id, string $hex)
Maybe something like this instead:
```php
#[ApiResource(normalizationContext: ['groups' => ['read']])]
class Color
{
    public function __construct(
        #[ApiProperty(identifier: true)] 
        #[Groups('read')] 
        public int $id, // public was missing
        
        #[Groups('read')] 
        public string $hex
    ) {
    }
}
```

2022-01-11 08:13 UTC, mtarld commented on src/Validator/ApiResourceExist.php
>       * @psalm-suppress DocblockTypeContradiction
It seems that PHPStan is saying it can: `Error: src/Validator/ApiResourceExist.php:33:24: UnusedPsalmSuppress: This suppression is never used (see https://psalm.dev/207)`

https://github.com/mtarld/api-platform-ms-bundle/runs/4766873242?check_suite_focus=true

2022-01-11 11:09 UTC, Chris53897 commented on tests/Fixtures/App/src/Entity/Color.php
>      public function __construct(int $id, string $hex)
Thanks for the hint with the missing `public`. I updated them

2022-01-11 11:13 UTC, Chris53897 commented on src/Validator/ApiResourceExist.php
>       * @psalm-suppress DocblockTypeContradiction
Ok, i was not sure if you mean the whole class and connected class and tests. i did it now

2022-01-11 11:47 UTC, Chris53897 commented
PhpUnit Tests are running fine lokal (mac intel) with PHP 8.0.14 and 8.1.1.
But GitHub Actions are failing. I did not figured out why.

2022-01-14 08:57 UTC, mtarld requested changes
I think tests are working on your local instance because of your cache.
But by applying my suggestions on test resources and dtos, it should work!
Try to remove the cache before running those tests (`rm -rf var/cache/*`)

2022-01-14 08:57 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Puppy.php
> +        #[Groups('read')] public ?array $hairs = []
```suggestion
        #[Groups('read')]
        public ?array $hairs = [],
```

2022-01-14 08:57 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Puppy.php
> +    public function __construct(
```suggestion
    /**
     * @param Hair[]|null $hairs
     */
    public function __construct(
```

2022-01-14 08:57 UTC, mtarld commented on tests/Validator/ApiResourceExistValidatorTest.php
> -class ApiResourceExistValidatorTest extends KernelTestCase
Why that file was deleted?

2022-01-14 08:57 UTC, mtarld commented on tests/Fixtures/App/src/Dto/PuppyResourceDto.php
> +    public function __construct(public ?string $iri,
It needs to be like the other resources:
```php
/**
 * @param HairResourceDto[]|null $hairs
 */
public function __construct(
    public ?string $iri,
    public string $superName,
    public ?ColorResourceDto = null,
    // ...
) {
    $this->iri = $iri
}
```

2022-01-14 08:57 UTC, mtarld commented on tests/Fixtures/App/src/Dto/PuppyDto.php
> +                                public string $superName)
```suggestion
    public function __construct(
        public int $id,
        public string $superName,
    ) {
```

2022-01-14 08:57 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Color.php
> +        public string $hex
```suggestion
        public string $hex,
```

2022-01-14 08:57 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Hair.php
> +        public Color $color
```suggestion
        public Color $color,
```

2022-01-14 08:57 UTC, mtarld commented on tests/Fixtures/App/src/Dto/HairResourceDto.php
> +    public function __construct(public string $iri,
Same for every other constructor :slightly_smiling_face:

2022-01-14 08:57 UTC, mtarld commented on src/Validator/FormatEnabledValidator.php
> +    public function __construct(private array $enabledFormats)
```suggestion
    /**
     * @param list<string> $enabledFormats
     */
    public function __construct(private array $enabledFormats)
```

2022-01-14 08:57 UTC, mtarld commented on src/Dto/ApiResourceDtoTrait.php
> -    protected $iri;
This shouldn't be removed

2022-01-14 08:57 UTC, mtarld commented on src/Collection/PaginatedCollectionIterator.php
> +     * @throws RedirectionExceptionInterface
Can be removed (already extending the ExceptionInterface)

2022-01-14 08:57 UTC, mtarld commented on src/Collection/Collection.php
> +        private ?Pagination $pagination = null
```suggestion
        private ?Pagination $pagination = null,
```
Same for toher occurrences, it eases the future diff

2022-01-14 08:57 UTC, mtarld commented on src/Validator/ApiResourceExist.php
> -class ApiResourceExist extends Constraint
Why did you remove it?

2022-01-18 09:03 UTC, Chris53897 commented on src/Dto/ApiResourceDtoTrait.php
> -    protected $iri;
If `iri` is defined in `ApiResourceDtoTrait` and in the promoted constructor in PuppyResourceDto i get the following error. I tried to changed the test to make it work. But now success until now. Sorry

PHP Fatal error:  Mtarld\ApiPlatformMsBundle\Tests\Fixtures\App\src\Dto\PuppyResourceDto and Mtarld\ApiPlatformMsBundle\Dto\ApiResourceDtoTrait define the same property ($iri) in the composition of Mtarld\ApiPlatformMsBundle\Tests\Fixtures\App\src\Dto\PuppyResourceDto. However, the definition differs and is considered incompatible. Class was composed in /Users/georg/PhpStorm/open-source/api-platform-ms-bundle/tests/Fixtures/App/src/Dto/PuppyResourceDto.php on line 11

2022-01-25 15:50 UTC, mtarld commented on src/Dto/ApiResourceDtoTrait.php
> -    protected $iri;
Gonna have a look ASAP :slightly_smiling_face:

2022-01-28 09:40 UTC, mtarld commented on src/Collection/Collection.php
> +        $this->microservice = null;
You can safely remove that line (as it's defined line 23)

2022-01-28 09:40 UTC, mtarld commented on src/Collection/PaginatedCollectionIterator.php
> +    public function __construct(private GenericHttpClient $httpClient,
Little code syntax issue :slightly_smiling_face:

2022-01-28 09:40 UTC, mtarld commented on src/Collection/PaginatedCollectionIterator.php
> +     * @throws RedirectionExceptionInterface
Same for `ServerExceptionInterface`

2022-01-28 09:40 UTC, mtarld commented on src/Collection/Pagination.php
> +                                private string $first,
Code syntax issue

2022-01-28 09:40 UTC, mtarld commented on src/Controller/ApiResourceExistenceCheckerAction.php
> +        private ValidatorInterface $validator
```suggestion
        private ValidatorInterface $validator,
```

2022-01-28 09:40 UTC, mtarld commented on src/Dto/ApiResourceDtoTrait.php
> -    protected $iri;
Ok I think I found it, it's because when using the `ApiResourceDtoTrait`, we can't use property promotion for `iri`, instead, we must set it the "old school way":
```php
class Foo {
    public function __construct(
        ?string $iri,
        private Bar $otherProperty,
        // ...
    ) {
        $this->iri = $iri
    }
}

2022-01-28 09:40 UTC, mtarld commented on src/Dto/ApiResourceExistenceCheckerPayload.php
> +    public array $iris;
You still allowed to put PHP attributes even open properties that are promoted

2022-01-28 09:40 UTC, mtarld commented on src/Validator/ApiResourceExistValidator.php
> -class ApiResourceExistValidator extends ConstraintValidator
We can't remove that validator (and its constraint) :slightly_smiling_face:

2022-01-30 15:34 UTC, Chris53897 commented on src/Dto/ApiResourceDtoTrait.php
> -    protected $iri;
That was the reason i did not use property promotion constructor there at the first commits ;)
But i guess i did not communicate  that clerly. Sorry

2022-01-30 15:37 UTC, Chris53897 commented on src/Collection/PaginatedCollectionIterator.php
> +    public function __construct(private GenericHttpClient $httpClient,
I am not sure what you mean here. But i will run cs-fixer

2022-01-30 15:44 UTC, Chris53897 commented on src/Validator/ApiResourceExistValidator.php
> -class ApiResourceExistValidator extends ConstraintValidator
Sorry, i  did unterstood you wrong. I added them all back. I hope it is correct now.

2022-01-30 15:46 UTC, Chris53897 commented on src/Validator/ApiResourceExistValidator.php
> -class ApiResourceExistValidator extends ConstraintValidator
`You still allowed to put PHP attributes even open properties that are promoted`
> What am i supposed to do here? I think is clear to read the way it actual is.

2022-01-30 15:48 UTC, Chris53897 commented on src/Validator/ApiResourceExist.php
> -class ApiResourceExist extends Constraint
I added them back. see comment below

2023-04-05 14:42 UTC, mtarld commented
Closed in favor of https://github.com/mtarld/api-platform-ms-bundle/pull/82, thank you, @Chris53897 :slightly_smiling_face:

2023-04-05 14:42 UTC, closed without merging