Feat/drop php 7
mtarld/api-platform-ms-bundle pull request #82
Opened 2023-03-30 08:46 UTC by artemis-mm

- migrating to php8 style constructors and dependency injection
- use php8 attributes
- temporarily restrict to Symfony 6.0 because tests fail for versions above

2023-03-30 09:00 UTC, artemis-mm commented
Should've mentioned, that the php 8.0 will fail as well as the 7 tests, because of the requirements of the packages, which jumped straight to 8.1

2023-03-30 10:31 UTC, mtarld requested changes
Nice job! This is a very good first step :muscle:

2023-03-30 10:31 UTC, mtarld commented on .gitignore
> +.idea
This can be removed and placed in your global gitignore instead

2023-03-30 10:31 UTC, mtarld commented on composer.json
> +    "symfony/http-client": ">=6.0 <6.1",
```suggestion
    "symfony/http-client": "^6.0",
```

Mayve you can do like that and leverage [conflict](https://getcomposer.org/doc/04-schema.md#conflict)?

2023-03-30 10:31 UTC, mtarld commented on src/Collection/Pagination.php
> +    public function __construct(private readonly string $current, private readonly string $first, private readonly string $last, private readonly ?string $previous, private readonly ?string $next)
Can you multiline constructors to improve readability? :slightly_smiling_face:

2023-03-30 10:31 UTC, mtarld commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +    final public const FORMAT_CONFIGURATION_FILE_MAPPING = [
I think that soft final classes (`@final`) might become hard final classes (`final class`), but that's for another PR!

2023-03-30 10:31 UTC, mtarld commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +                array_map(static fn (array $microservice): string => $microservice['format'], array_filter($config['microservices'], static fn (array $microservice): bool => isset(self::FORMAT_CONFIG
Can you multiline it?

2023-03-30 10:31 UTC, mtarld commented on src/Dto/ApiResourceExistenceCheckerPayload.php
>       * @Assert\All({
Why it isn't converted?

2023-03-30 10:31 UTC, mtarld commented on src/Dto/ApiResourceExistenceCheckerView.php
> +    public array $existences;
This can be readonly

2023-03-30 10:31 UTC, mtarld commented on src/HttpClient/GenericHttpClient.php
> +     * @param \Mtarld\ApiPlatformMsBundle\HttpClient\AuthenticationHeaderProviderInterface[] $authenticationHeaderProviders
```suggestion
     * @param list<AuthenticationHeaderProviderInterface> $authenticationHeaderProviders
```

2023-03-30 10:31 UTC, mtarld commented on src/Microservice/Microservice.php
> +         * @Mtarld\ApiPlatformMsBundle\Validator\FormatEnabled
This must be updated to an attribute instead :slightly_smiling_face:

2023-03-30 10:31 UTC, mtarld commented on src/Validator/ApiResourceExist.php
>   * @Annotation
I think we can remove the annotation support now :tada:

2023-03-30 10:31 UTC, mtarld commented on src/Validator/FormatEnabled.php
>   * @Annotation
Same here

2023-03-30 10:31 UTC, mtarld commented on src/Validator/FormatEnabledValidator.php
> +    public function __construct(private readonly array $enabledFormats)
At some point, it could be great to describe arrays everywhere (`list<string>` here)
But that's for another PR!

2023-03-30 10:31 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Color.php
>       * @ApiProperty(identifier=true)
This might be attribute now

2023-03-30 10:31 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Hair.php
>       * @ApiProperty(identifier=true)
Same here and everywhere

2023-03-30 10:31 UTC, mtarld commented on psalm.xml
> -        totallyTyped="false"
Why removing it?

2023-03-30 10:31 UTC, mtarld commented on rector.php
> +        SensiolabsSetList::FRAMEWORK_EXTRA_61,
As we don't use SensioFrameworkExtraBundle, you can remove it

2023-03-30 10:31 UTC, mtarld commented on rector.php
> +    $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);
This can be for multiline :slightly_smiling_face:

2023-03-30 10:31 UTC, mtarld commented on phpmd.xml
> +        </properties>
Which imports are missing?

2023-03-30 10:31 UTC, mtarld commented on composer.json
> +    "symfony/browser-kit": "^5.4|~6.0",
You can drop 5.4 there

2023-03-30 10:31 UTC, mtarld commented on composer.json
> +    "symfony/browser-kit": "^5.4|~6.0",
```suggestion
    "symfony/browser-kit": "^6.0",
```

(With conflicts as well)

2023-03-30 10:37 UTC, artemis-mm commented on src/Collection/Pagination.php
> +    public function __construct(private readonly string $current, private readonly string $first, private readonly string $last, private readonly ?string $previous, private readonly ?string $next)
Will do (for every other construct as well)

2023-03-30 10:37 UTC, artemis-mm commented on src/DependencyInjection/ApiPlatformMsExtension.php
> +    final public const FORMAT_CONFIGURATION_FILE_MAPPING = [
Wasn't shure about that one, so I left it to the soft ones

2023-03-30 10:38 UTC, artemis-mm commented on .gitignore
> +.idea
Will do

2023-03-30 10:38 UTC, artemis-mm commented on psalm.xml
> -        totallyTyped="false"
Got an error from psalm that this option is deprecated and failed

2023-03-30 10:43 UTC, artemis-mm commented on psalm.xml
> -        totallyTyped="false"
ERROR: ConfigIssue - ]8;;file:///Users/martinmeese/PhpstormProjects/api-platform-ms-bundle/psalm.xml#L3\psalm.xml:3:9]8;;\ - Attribute "totallyTyped" is deprecated and is going to be removed in the next major version (see https://psalm.dev/271)
        totallyTyped="false"


------------------------------
1 errors found

2023-03-30 11:40 UTC, artemis-mm commented on phpmd.xml
> +        </properties>
That's the contradiction between php-cs-fixer and phpmd. if that's not set to ignore the global imports e.g. `\RuntimeException` will lead to an error because there's no explicit use statement `Missing class import via use statement (line 'xxx', column 'yyy')`

2023-04-04 07:57 UTC, mtarld requested changes

2023-04-04 07:57 UTC, mtarld commented on .gitignore
> +vendor/
Missing empty line

2023-04-04 07:57 UTC, mtarld commented on composer.json
> +    "phpunit/phpunit": "^8.5.23|^9.5",
Can't we keep `^9.5` only?

2023-04-04 07:57 UTC, mtarld commented on src/Dto/ApiResourceExistenceCheckerPayload.php
> +use phpDocumentor\Reflection\Type;
Unexpected use I guess

2023-04-04 07:57 UTC, mtarld commented on composer.json
> +    "api-platform/core": "^3",
```suggestion
    "api-platform/core": "^3.0",
```
To prevent an unexpected upgrade to 4.x

2023-04-04 07:57 UTC, mtarld commented on src/Serializer/JsonApi/CollectionDenormalizer.php
> -            $element = $this->denormalizer->denormalize(['data' => $elementData], $enclosedType, $this->getFormat(), $context);
Why did you remove the context there?

2023-04-04 07:57 UTC, mtarld commented on src/Serializer/Hal/CollectionDenormalizer.php
> -            $element = $this->denormalizer->denormalize($elementData, $enclosedType, $this->getFormat(), $context);
Same here

2023-04-04 07:57 UTC, mtarld commented on src/Serializer/AbstractCollectionDenormalizer.php
> -            $rawElement = $this->denormalizer->denormalize($elementData, $enclosedType, $this->getFormat(), $context);
And here

2023-04-04 07:57 UTC, mtarld commented on src/Serializer/AbstractApiResourceDenormalizer.php
> -        return $this->denormalizer->denormalize($data, $type, $this->getFormat(), $context);
Why did you remove the context here?

2023-04-04 07:57 UTC, mtarld commented on src/Controller/ApiResourceExistenceCheckerAction.php
> -        if (null === $contentType = $request->getContentTypeFormat()) {
`getContentType` is deprecated in favor of `getContentTypeFormat`

2023-04-04 07:57 UTC, mtarld commented on tests/Fixtures/App/src/Entity/Puppy.php
> +        new Post(uriTemplate: 'puppies'),
Can we keep the defaults?

2023-04-04 08:13 UTC, artemis-mm commented on src/Serializer/JsonApi/CollectionDenormalizer.php
> -            $element = $this->denormalizer->denormalize(['data' => $elementData], $enclosedType, $this->getFormat(), $context);
Don't know why this got dropped, on my local branch I added it back already

2023-04-04 08:22 UTC, artemis-mm commented on composer.json
> +    "phpunit/phpunit": "^8.5.23|^9.5",
Sure

2023-04-05 13:52 UTC, mtarld commented on composer.json
> +    "doctrine/inflector": "^2.0",
Sorry, it's a miss of mine, could you remove it?

2023-04-05 13:56 UTC, artemis-mm commented on composer.json
> +    "doctrine/inflector": "^2.0",
Should be "doctrine/annotations": "^2.0" !? or back to ^1.7 ?

2023-04-05 14:12 UTC, mtarld commented on composer.json
> +    "doctrine/inflector": "^2.0",
You can fully remove the line I guess

2023-04-05 14:40 UTC, mtarld approved these changes
LGTM! Many thanks @artemis-mm :muscle:

2023-04-05 14:40 UTC, merged